[project]
name = "splinter"
version = "0.1.0"
dependencies = ["mypy", "django-stubs", "django-filter-stubs", "vstutils"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"